version: '1'

services:
  mirotalk:
    image: fluent:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluent
    hostname: fluent
    volumes:
      - .env:/usr/src/app/.env:ro
    restart: unless-stopped
    ports:
      - "3000:3000"